[project]
name = "telemetry-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "aiokafka>=0.12.0",
    "pydantic>=2.11.7",
]
